### ISSUE TITLE
Dateparser doesnt work with latest regex on m1 mac

### ISSUE THREAD

**Issue by anshuman852** [scrapinghub/dateparser#1004] opened 2021-10-20 14:26 UTC
To fix this i had to downgrade regex to `regex==2021.9.30`
Here is the log- `Python 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:19) [Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dateparser/__init__.py", line 3, in <module>
    from .date import DateDataParser
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dateparser/date.py", line 6, in <module>
    import regex as re
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/_regex.cpython-310-darwin.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/_regex.cpython-310-darwin.so: code signature in (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/regex/_regex.cpython-310-darwin.so) not valid for use in process using Library Validation: Trying to load an unsigned library
`

**Comment by anshuman852** [comment] 2021-10-20 14:27
Got the info from https://github.com/aws/aws-sam-cli/issues/3370#issuecomment-946012467

**Comment by Gallaecio** [comment] 2022-10-21 15:57
The latest regex is 2022-09-13, could you check with that one?

**Comment by Gallaecio** [comment] 2022-10-21 16:02
Closing as a duplicate of https://github.com/scrapinghub/dateparser/issues/1052 (this issue is older, but the linked one has a longer conversation)

**Closed by Gallaecio** 2022-10-21 16:02 UTC
Labels: upstream
