### ISSUE TITLE
Dateparser wrong date parsing for IST timezone

### ISSUE THREAD

**Issue by bazingarj** [scrapinghub/dateparser#636] opened 2020-03-19 07:23 UTC
```
d = '2018-02-17 16:15:36.519 IST'
j = dateparser.parse( d, settings = { 'TIMEZONE' :  'Asia/Kolkata' } )
print ( d ) # 2018-02-17 16:15:36.519 IST
print ( j ) # 2018-02-17 19:45:36.519000+05:30
```
It must print  - 2018-02-17 16:15:36.519000+05:30

then i debugged the value i get after parse  in j without timezone

```
d = '2018-02-17 16:15:36.519 IST'
j = dateparser.parse( d )
print ( j ) # 2018-02-17 16:15:36.519000+02:00
```
Why it is +02:00, it must be +05:30

**Comment by bazingarj** [comment] 2020-03-19 08:35
Accept PR #637 then close this issue

**Comment by asadurski** [comment] 2020-03-19 16:40
Hello @bazingarj, it's a duplicate of https://github.com/scrapinghub/dateparser/issues/580 and https://github.com/scrapinghub/dateparser/issues/609. IST resolves to India Standard Time and Israel Standard Time (and even to Irish Standard Time, for the sake of precision).

Do you have any other suggestions for dealing with this issue other than overwriting IST?

**Comment by noviluni** [comment] 2020-05-06 11:47
Closing this ticket as duplicated of https://github.com/scrapinghub/dateparser/issues/580

**Closed by noviluni** 2020-05-06 11:47 UTC
