### ISSUE TITLE
Times containing decimals not understood intuitively

### ISSUE THREAD

**Issue by JellyWX** [scrapinghub/dateparser#766] opened 2020-08-08 21:20 UTC
Using decimals as in `0.5 minutes` or `1.5 hours` are not understood 'correctly' (intuitively) by dateparser.

Reproducing:
1. clone repo as of now
2. create fresh venv
3. pip install .
4:
    import dateparser
    dateparser.parse('now') - dateparser.parse('0.5 minutes')

I would expect this to produce 30 seconds but instead it produces 5 minutes (300 seconds). Whilst decimals are not particularly common, it might be desireable to clear up this behaviour to behave slightly more intuitively.

This could also be an artifact of another real language that prefers to use periods rather than colons to delimit times (if anyone can confirm?)

Python version: 3.8.2 GCC 9.3.0 on Linux
Dateparser: from master
Regex: 2.5.83
Pytz: 2020.1
Six: 1.15.0

**Comment by Gallaecio** [comment] 2020-08-10 12:14
Duplicate of #753

**Closed by Gallaecio** 2020-08-10 12:14 UTC
