### ISSUE TITLE
Email date header fials to parse

### ISSUE THREAD

**Issue by seanthegeek** [scrapinghub/dateparser#587] opened 2019-11-11 22:21 UTC
The following code returns `None`, instead of a parsed date.

```python
import dateparser

date = "Mon, 11 Nov 2019 22:16:45 -0000"
dateparser.parse(date)
```

Is seems `dateparser` does not like the `-0000` offset. Removing the offset, or using a different offset works fine,

Another example that fails:

> Mon, 11 Nov 2019 18:31:32 +0100 (CET)

The string parses correctly when (CET) is removed.

**Comment by Gallaecio** [comment] 2019-12-12 13:57
Duplicate of #402

**Closed by Gallaecio** 2019-12-12 13:57 UTC
