### ISSUE TITLE
French date parsed wrongly

### ISSUE THREAD

**Issue by dabega** [scrapinghub/dateparser#960] opened 2021-08-11 12:13 UTC
Didn't try all months/combinations, but strings with the month of September are parsed wrongly.
Tried with and without specifying language used

INPUT: "jeu. 2 sept. 10:34"
EXPECTED: datetime.datetime(2021, 9, 2, 10, 34)
OUTPUT: datetime.datetime(2021, 7, 2, 10, 34)

Changing the input string to "jeu. 2 sep. 10:34" gets the correct result

**Comment by dabega** [comment] 2021-08-11 12:43
Just verified in the language data, "sept" is (as it should be) specified as an alias of September.
Maybe the clue to the bug is that "sept" in french means seven (7), and somewhere in the parsing pipeline it is prioritized over the month alias.

**Comment by noviluni** [comment] 2021-08-19 06:45
Hi @dabega,
you are right, it is because sept is wrongly translated to 7. I don't know any useful workaround apart from doing something like:
`text.replace('sept.', 'sep.')` or `text.replace('sept.', 'septembre')`, which is not desirable.

There's an open issue here: #676 to discuss how to handle this, and the same issue was reported here: #819.

We will probably make optional the natural number detection when integrating number-parser (https://github.com/scrapinghub/dateparser/pull/711), but this won't fix the root issue (#676).


I will close this as duplicate of: #819. Thank you for reporting!

**Closed by noviluni** 2021-08-19 06:45 UTC
