### ISSUE TITLE
PytzUsageWarning: The localize method is no longer necessary

### ISSUE THREAD

**Issue by atompie** [scrapinghub/dateparser#1025] opened 2021-12-04 00:15 UTC
When parsing date.

PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)

**Comment by neon-ninja** [comment] 2021-12-19 22:38
Duplicate of https://github.com/scrapinghub/dateparser/issues/1013

**Comment by lopuhin** [comment] 2021-12-21 15:45
Closing as a duplicate of #1013, thanks @neon-ninja

**Closed by lopuhin** 2021-12-21 15:45 UTC
