### ISSUE TITLE
Timezone offset `-0000` is not parsable, but `+0000` is.

### ISSUE THREAD

**Issue by alertedsnake** [scrapinghub/dateparser#458] opened 2018-10-22 19:32 UTC
Weird, I know, but some people write it like that.  Like Github's status RSS feed:
```
<item>
  <title>
    [major] We continue to work to migrate a data storage system in order to restore access to GitHub.com.
  </title>
  <link>https://status.github.com</link>
  <description>
    We continue to work to migrate a data storage system in order to restore access to GitHub.com.
  </description>
  <pubDate>Mon, 22 Oct 2018 01:22:22 -0000</pubDate>
  <guid>https://status.github.com/#2143</guid>
</item>
```

**Comment by Gallaecio** [comment] 2019-12-11 12:44
Duplicate of #402

**Closed by Gallaecio** 2019-12-11 12:44 UTC
