### ISSUE TITLE
Incompatibility with recent regex

### ISSUE THREAD

**Issue by nicsuzor** [scrapinghub/dateparser#1085] opened 2022-10-13 01:27 UTC
I upgraded regex, and dateparser broke.

Running Python 3.10.3, I've tried with regex==2022.7.24, 2022.8.17, 2022.9.11, 2022.9.13
```
Python 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 13:07:40) [MSC v.1929 64 bit (AMD64)] on win32
>>> from dateparser import parse
>>> parse('july')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\src\venv310\lib\site-packages\dateparser\conf.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "E:\src\venv310\lib\site-packages\dateparser\__init__.py", line 61, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "E:\src\venv310\lib\site-packages\dateparser\date.py", line 428, in get_date_data
    parsed_date = _DateLocaleParser.parse(
  File "E:\src\venv310\lib\site-packages\dateparser\date.py", line 178, in parse
    return instance._parse()
  File "E:\src\venv310\lib\site-packages\dateparser\date.py", line 182, in _parse
    date_data = self._parsers[parser_name]()
  File "E:\src\venv310\lib\site-packages\dateparser\date.py", line 196, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "E:\src\venv310\lib\site-packages\dateparser\date.py", line 234, in _get_translated_date
    self._translated_date = self.locale.translate(
  File "E:\src\venv310\lib\site-packages\dateparser\languages\locale.py", line 131, in translate
    relative_translations = self._get_relative_translations(settings=settings)
  File "E:\src\venv310\lib\site-packages\dateparser\languages\locale.py", line 158, in _get_relative_translations
    self._generate_relative_translations(normalize=True))
  File "E:\src\venv310\lib\site-packages\dateparser\languages\locale.py", line 172, in _generate_relative_translations
    pattern = DIGIT_GROUP_PATTERN.sub(r'?P<n>\d+', pattern)
  File "E:\src\venv310\lib\site-packages\regex\regex.py", line 710, in _compile_replacement_helper
    is_group, items = _compile_replacement(source, pattern, is_unicode)
  File "E:\src\venv310\lib\site-packages\regex\_regex_core.py", line 1737, in _compile_replacement
    raise error("bad escape \\%s" % ch, source.string, source.pos)
regex._regex_core.error: bad escape \d at position 7
```

Works fine for regex==2021.8.28
```
Python 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 13:07:40) [MSC v.1929 64 bit (AMD64)] on win32
>>> from dateparser import parse
>>> parse('july')
E:\src\venv310\lib\site-packages\dateparser\date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)
datetime.datetime(2022, 7, 13, 0, 0)
```

**Comment by nicsuzor** [comment] 2022-10-13 01:28
I'm sorry, I had a quick look before posting this, but a more thorough search shows this is a known bug: https://github.com/scrapinghub/dateparser/issues/1045

**Comment by Gallaecio** [comment] 2022-10-13 03:04
Can you confirm things work with the latest version of dateparser? If so, please feel free to close this issue.

**Comment by anbiAMF** [comment] 2022-10-15 15:28
Hi
using regex = 2022.3.2 and dateparser = 1.1.1, I get the same issue
  File "C:\Users\xxxcon\.conda\envs\py39_web\lib\site-packages\regex\_regex_core.py", line 1737, in _compile_replacement
    raise error("bad escape \\%s" % ch, source.string, source.pos)

**Comment by Gallaecio** [comment] 2022-10-15 19:36
Thank you! Closing as a duplicate of #1045, which I have just reopened.

**Closed by Gallaecio** 2022-10-15 19:36 UTC
