### ISSUE TITLE
Handling of W3C Date and Time Formats

### ISSUE THREAD

**Issue by Ash-Crow** [scrapinghub/dateparser#818] opened 2020-10-26 16:46 UTC
Hello, while trying to compare if dateparser gave the same results as the [date parsing function of feedparser](https://pythonhosted.org/feedparser/date-parsing.html), I found some strange results regarding the handling of the standard dates of the W3C as defined in their [Date and Time Formats note](https://www.w3.org/TR/NOTE-datetime)

```
>>> w3cdtf_formats = ["2020", "2020-08", "2020-08-11", "2020-08-11T09:01Z", "2020-08-11T09:01+00:00", "2020-08-11T09:01-05:00", "2020-08-11T09:01:02Z", "2020-08-11T09:01:02+00:00", "2020-08-11T09:01:02-05:00", "2020-08-11T09:01:02.45Z", "2020-08-11T09:01:02.45+00:00", "2020-08-11T09:01:02.45-05:00"]
>>> for f in w3cdtf_formats:
...     dateparser.parse(f).utctimetuple()
... 
time.struct_time(tm_year=2020, tm_mon=10, tm_mday=26, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=300, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=10, tm_mday=8, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=282, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=11, tm_mday=8, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=6, tm_yday=313, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=11, tm_mday=8, tm_hour=9, tm_min=1, tm_sec=0, tm_wday=6, tm_yday=313, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=11, tm_mday=8, tm_hour=9, tm_min=1, tm_sec=0, tm_wday=6, tm_yday=313, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=11, tm_mday=8, tm_hour=14, tm_min=1, tm_sec=0, tm_wday=6, tm_yday=313, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=11, tm_mday=8, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=6, tm_yday=313, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=11, tm_mday=8, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=6, tm_yday=313, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=11, tm_mday=8, tm_hour=14, tm_min=1, tm_sec=2, tm_wday=6, tm_yday=313, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=11, tm_mday=8, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=6, tm_yday=313, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=11, tm_mday=8, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=6, tm_yday=313, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=11, tm_mday=8, tm_hour=14, tm_min=1, tm_sec=2, tm_wday=6, tm_yday=313, tm_isdst=0)
```
It seems to default to a "YYYY-DD-MM" date format that I am not sure is used anywhere in the world ([Wikipedia doesn't know it anyway](https://en.wikipedia.org/wiki/Date_format_by_country)).

I would expect to default to "YYYY-MM-DD" when the year is first. I can set `'DATE_ORDER': 'YMD'` to fix it, but then I got an issue with the first example of the feedparser formats: `Thu, 01 Jan 04 19:48:21 GMT: -1092 days, 0:00:00` is now interpreted as `time.struct_time(tm_year=2001, tm_mon=1, tm_mday=4, tm_hour=19, tm_min=48, tm_sec=21, tm_wday=3, tm_yday=4, tm_isdst=0)` instead of `time.struct_time(tm_year=2004, tm_mon=1, tm_mday=1, tm_hour=19, tm_min=48, tm_sec=21, tm_wday=3, tm_yday=1, tm_isdst=0)`

I would also expect "2020-08" to be interpreted as "YYYY-MM" and not "YYYY-DD" (especially as dateformat does not manage the ISO 8601 "YYYY-DDD" format, ie "1981-095" is not interpreted as equivalent to "1981-04-05" and thus returns none)

Also, I would prefer  "2020" to be interpreted as "2020-01-01" and I can fix this for the day with `'PREFER_DAY_OF_MONTH': 'first'`, but there doesn't seem to be an equivalent for the month:

```
>>> for f in w3cdtf_formats:
...     dateparser.parse(f, settings=settings).utctimetuple()
time.struct_time(tm_year=2020, tm_mon=10, tm_mday=1, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=275, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=1, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=5, tm_yday=214, 
```

**Comment by noviluni** [comment] 2020-10-27 14:09
Hi @Ash-Crow, 

thank you for checking this. Could you confirm which version of `dateparser` did you used to do this test?

I tried with `dateparser==0.7.6` (and the version in master) and I got different results:

```
>>> import dateparser
>>> w3cdtf_formats = ["2020", "2020-08", "2020-08-11", "2020-08-11T09:01Z", "2020-08-11T09:01+00:00", "2020-08-11T09:01-05:00", "2020-08-11T09:01:02Z", "2020-08-11T09:01:02+00:00", "2020-08-11T09:01:02-05:00", "2020-08-11T09:01:02.45Z", "2020-08-11T09:01:02.45+00:00", "2020-08-11T09:01:02.45-05:00"]

>>> for f in w3cdtf_formats:
>>>    print(dateparser.parse(f).utctimetuple())

time.struct_time(tm_year=2020, tm_mon=10, tm_mday=27, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=1, tm_yday=301, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=27, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=240, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=1, tm_yday=224, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=0, tm_wday=1, tm_yday=224, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=0, tm_wday=1, tm_yday=224, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=14, tm_min=1, tm_sec=0, tm_wday=1, tm_yday=224, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=14, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)
time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=14, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)
```

I would like to know the version you used to discard possible issues with the local configuration, etc.

**Comment by Ash-Crow** [comment] 2020-11-05 13:17
Hi, I used dateparser version 0.7.6 too. 

It might be an issue with the locale ?

>>> print(f"dateparser version: {pkg_resources.get_distribution('dateparser').version}")
dateparser version: 0.7.6
>>> locale.getlocale()
('fr_FR', 'UTF-8')

That said, I don't have the problem anymore, I don't understand why. I have recreated the virtualenv I was working in, but I didn't change any setting, so it's strange.

>>> for f in w3cdtf_formats:
...     print(f, dateparser.parse(f).utctimetuple())
... 
2020 time.struct_time(tm_year=2020, tm_mon=11, tm_mday=5, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=310, tm_isdst=0)
2020-08 time.struct_time(tm_year=2020, tm_mon=8, tm_mday=5, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=2, tm_yday=218, tm_isdst=0)
2020-08-11 time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=1, tm_yday=224, tm_isdst=0)
2020-08-11T09:01Z time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=0, tm_wday=1, tm_yday=224, tm_isdst=0)
2020-08-11T09:01+00:00 time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=0, tm_wday=1, tm_yday=224, tm_isdst=0)
2020-08-11T09:01-05:00 time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=14, tm_min=1, tm_sec=0, tm_wday=1, tm_yday=224, tm_isdst=0)
2020-08-11T09:01:02Z time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)
2020-08-11T09:01:02+00:00 time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)
2020-08-11T09:01:02-05:00 time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=14, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)
2020-08-11T09:01:02.45Z time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)
2020-08-11T09:01:02.45+00:00 time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)
2020-08-11T09:01:02.45-05:00 time.struct_time(tm_year=2020, tm_mon=8, tm_mday=11, tm_hour=14, tm_min=1, tm_sec=2, tm_wday=1, tm_yday=224, tm_isdst=0)

**Comment by noviluni** [comment] 2020-11-06 10:50
hmmm... I don't know @Ash-Crow .

As we are not able to reproduce this issue anymore I will close this ticket, but if you find the root cause or you have any new hint please, feel free to comment here, re-open the issue or open a new issue. :slightly_smiling_face: 

Thanks!

**Closed by noviluni** 2020-11-06 10:50 UTC
