### ISSUE TITLE
Dateparser fails for strings with date and non date integer

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/dateparser#586] opened 2019-11-08 18:02 UTC
```
dateparser 0.7.2

parse("57, 1990")
~/miniconda3/envs/webrcnn_dev/lib/python3.7/site-packages/dateparser/parser.py in parse(cls, datestring, settings)
    445     def parse(cls, datestring, settings):
    446         tokens = tokenizer(datestring)
--> 447         po = cls(tokens.tokenize(), settings)
    448         dateobj = po._results()
    449 

>>>~/miniconda3/envs/webrcnn_dev/lib/python3.7/site-packages/dateparser/parser.py in __init__(self, tokens, settings)
    272                 if type == 0:
    273                     params.update({attr: int(token)})
--> 274                     datetime(**params)
    275                     setattr(self, '_token_%s' % attr, token)
    276                     setattr(self, attr, int(token))
TypeError: function missing required argument 'day' (pos 3)
```

I expect it to extract `1990`.

**Comment by Gallaecio** [comment] 2019-12-12 13:52
Duplicate of #339

**Closed by Gallaecio** 2019-12-12 13:52 UTC
Labels: Type: Bug
