### ISSUE TITLE
Concurrency issues resulting in TypeError: unsupported operand type(s) for -: 'NoneType' and 'relativedelta'

### ISSUE THREAD

**Issue by andrek-data-axle** [scrapinghub/dateparser#813] opened 2020-10-16 13:57 UTC
I am assuming its a concurrency issue because the only way I can get it to fail is running multiple calls to dateparser.parse('14 days ago UTC') on separate threads.

```
  File "/var/app/current/credit/users/services/profile.py", line 67, in add_profile
    date_viewed__gt=dateparser.parse('14 days ago UTC')
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/dateparser/conf.py", line 85, in wrapper
    return f(*args, **kwargs)
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/dateparser/__init__.py", line 53, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/dateparser/date.py", line 418, in get_date_data
    locale, date_string, date_formats, settings=self._settings)
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/dateparser/date.py", line 194, in parse
    return instance._parse()
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/dateparser/date.py", line 198, in _parse
    date_obj = self._parsers[parser_name]()
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/dateparser/date.py", line 212, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/dateparser/freshness_date_parser.py", line 149, in get_date_data
    date, period = self.parse(date_string, settings)
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/dateparser/freshness_date_parser.py", line 94, in parse
    date, period = self._parse_date(date_string, settings.PREFER_DATES_FROM)
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/dateparser/freshness_date_parser.py", line 134, in _parse_date
    date = self.now - td
TypeError: unsupported operand type(s) for -: 'NoneType' and 'relativedelta'
```

**Comment by abkonsta** [comment] 2020-10-16 15:39
I monkey patched in my project and was able to stress-test it with no more concurrency issues in freshness_date_parser
Pull request submitted.

**Comment by Gallaecio** [comment] 2020-10-30 21:17
[dateparser is not thread-safe](https://github.com/scrapinghub/dateparser/issues/441).

**Comment by abkonsta** [comment] 2020-10-30 22:56
But it can be made to be...

**Comment by Gallaecio** [comment] 2020-11-04 21:47
Shall we close this and keep just https://github.com/scrapinghub/dateparser/issues/441 to track work to make it thread-safe?

**Comment by abkonsta** [comment] 2020-11-04 21:57
I was going to resubmit my pull request with the recommended edits.

**Comment by noviluni** [comment] 2020-11-22 15:42
Closing as duplicate of #441. I hope this PR: https://github.com/scrapinghub/dateparser/pull/834 would fix this once and for all :)

Thanks for providing feedback!

**Closed by noviluni** 2020-11-22 15:42 UTC
