### ISSUE TITLE
Dateparser throws module not found error becasue of regex module

### ISSUE THREAD

**Issue by aorfanos1** [scrapinghub/dateparser#505] opened 2019-02-19 19:52 UTC
The dateparser module is currently not building (python 3.6.1) (dateparser 0.7.1), because of the latest regex module update (2019.02.19) - our fix for this was to hardcode the regex version to a recent, but not broken point in time (2019.02.07). Just making you aware and hoping that we get a real fix for this soon. Thanks

**Comment by NickScottKortical** [comment] 2019-02-19 21:34
This looks to be caused by the setup.py not having fixed requirement versions whereas the requirements.txt file does. As a result because the regex module just released a broken package its broken the dateparser module installed via the setup.py.

**Comment by asadurski** [comment] 2019-02-20 12:49
I can see that the problem has already been fixed in regex repo (https://bitbucket.org/mrabarnett/mrab-regex/issues/314/import-error-no-module-named), with 2019.02.20 version released.
Thanks for the pointers @NickScottKortical, as you said, we'll need to pin the package versions in setup too.

**Comment by kishan3** [comment] 2019-12-20 11:38
> I can see that the problem has already been fixed in regex repo (https://bitbucket.org/mrabarnett/mrab-regex/issues/314/import-error-no-module-named), with 2019.02.20 version released.
> Thanks for the pointers @NickScottKortical, as you said, we'll need to pin the package versions in setup too.

Hi, @asadurski Can this be closed?

**Comment by Gallaecio** [comment] 2019-12-23 12:15
We might want to merge https://github.com/scrapinghub/dateparser/pull/600 first. Although it’s extremely unlikely it will save anyone at this point, so we might as well close both this and https://github.com/scrapinghub/dateparser/pull/600 (without merging).

**Comment by noviluni** [comment] 2020-01-17 11:37
Agree with @Gallaecio . It's better to explicity avoid that version.

**Closed** 2020-01-20 10:17 UTC
Labels: Status: Bug confirmed, Type: Maintenance
