### ISSUE TITLE
Is there a way to distinguish relative dates to absolute dates after parsing?

### ISSUE THREAD

**Issue by richiefeng** [scrapinghub/dateparser#452] opened 2018-10-08 23:08 UTC
As mentioned in the title, is there a way to tell if a datetime object is parsed through `freshness_parser` or others?

**Comment by Gallaecio** [comment] 2019-12-12 12:00
Duplicate of #579

Closing this one because #579, although newer, is a bit more complete and shaped as a feature request.

**Closed by Gallaecio** 2019-12-12 12:00 UTC
Labels: question
