### ISSUE TITLE
Thai does not respect DATE_ORDER

### ISSUE THREAD

**Issue by jleclanche** [scrapinghub/dateparser#589] opened 2019-11-12 09:58 UTC
```py
>>> parse('03/15/2559 05:13', languages=["th"], settings={"DATE_ORDER": "MDY"})
>>> parse('03/11/2559 05:13', languages=["th"], settings={"DATE_ORDER": "MDY"})
datetime.datetime(2559, 11, 3, 5, 13)
```

**Comment by Gallaecio** [comment] 2019-12-12 13:55
May this be a duplicate of #412?

**Comment by jleclanche** [comment] 2019-12-12 18:16
Doesn't really sound like it

**Comment by noviluni** [comment] 2019-12-15 20:57
It seems that this only happens with the last version:

dateparser 0.7.1

```
>>> parse('03/11/2559 05:13', languages=["th"], settings={"DATE_ORDER": "MDY"})                                                                     
datetime.datetime(2559, 3, 11, 5, 13)

```

dateparser 0.7.2

```
>>> parse('03/11/2559 05:13', languages=["th"], settings={"DATE_ORDER": "MDY"})                                                                     
datetime.datetime(2559, 3, 11, 5, 13)
```

**Comment by noviluni** [comment] 2020-03-06 17:40
It seems that this bug was introduced with this PR: https://github.com/scrapinghub/dateparser/pull/558

I will investigate it further and I will try to fix it.

**Closed** 2020-03-17 13:06 UTC
Labels: Type: Bug
