### ISSUE TITLE
error: venv/lib/python3.9/site-packages/dateparser/date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html

### ISSUE THREAD

**Issue by the1gofer** [scrapinghub/dateparser#1050] opened 2022-03-22 19:49 UTC
I'm getting 
` venv/lib/python3.9/site-packages/dateparser/date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html`

running 1.1.1, and I saw some similar discussions, but since I'm on the latest version it doesn't' look like it's fixed.   The code keeps going, so I guess it's a warning, but it's breaking other things for me.

**Comment by ian-barnes** [comment] 2022-04-21 08:26
Another duplicate of https://github.com/scrapinghub/dateparser/issues/1013

**Comment by gutsytechster** [comment] 2022-06-22 07:05
This can be closed now with the merge of #1062

**Closed by gutsytechster** 2022-06-22 07:05 UTC
