### ISSUE TITLE
Is this expected behaviour or a bug?

### ISSUE THREAD

**Issue by XtremeGood** [scrapinghub/dateparser#653] opened 2020-03-29 18:10 UTC
Is this expected behaviour or a bug?
![image](https://user-images.githubusercontent.com/40588378/77843943-945c7180-71bf-11ea-805e-161a52de6ac7.png)

_Originally posted by @XtremeGood in https://github.com/scrapinghub/dateparser/issues/643#issuecomment-605599249_

**Comment by XtremeGood** [comment] 2020-03-29 18:10
Let it be image this time, I ll be careful to avoid images from now onwards.

**Comment by noviluni** [comment] 2020-03-30 02:14
Hi @XtremeGood 

This is the expected behavior. `dateparser.parse` expects to receive a date string, not a text containing other (irrelevant) info. To find dates in longer texts you can use `dateparser.search_dates`. 

```
>>> print(search_dates('This tuesday it will be 30:12:1998'))
[('tuesday', datetime.datetime(2020, 3, 24, 0, 0)), ('30:12:1998', datetime.datetime(3012, 1, 9, 9, 8))]
```

Note that I think that `date_formats` is not supported by `search_dates`.

I close this issue as is a question and not a bug nor a new feature request. Feel free to re-open it if you consider it necessary or if this doesn't answer your question/problem.

Cheers!

**Closed by noviluni** 2020-03-30 02:14 UTC

**Comment by XtremeGood** [comment] 2020-03-30 03:45
ok thanks for the info.
