### ISSUE TITLE
Parsing time with "00:xx AM"

### ISSUE THREAD

**Issue by AnsgarSchmidt** [scrapinghub/dateparser#416] opened 2018-05-30 19:39 UTC
Hi
It seem parsing hour with 00 AM.

import dateparser

print(dateparser.parse("Saturday May 26, 2018  00:22 AM", date_formats=['dddd MMM D, yyyy  hh:mm tt']))
**None**

print(dateparser.parse("Saturday May 26, 2018  01:22 AM", date_formats=['dddd MMM D, yyyy  hh:mm tt']))
**2018-05-26 01:22:00**

The first call takes a second to return and only returns None and not an object.

**dateparser==0.7.0**

Greetings 
Ansi

**Comment by wRAR** [comment] 2018-09-20 16:28
Hello @AnsgarSchmidt , this seems to be a duplicate of #329.

**Closed by wRAR** 2018-09-20 16:28 UTC
Labels: duplicate
