### ISSUE TITLE
Fix dependencies version

### ISSUE THREAD

**Issue by Lenny415** [scrapinghub/dateparser#597] opened 2019-12-10 17:47 UTC
Hi there,
today my CI pipeline failed to build my docker image in which the python code references your lib.
It failed because gcc was missing from my image which was not the case the last time it was built (4 days ago).
After some investigation why the gcc was required, I found that regex was the culprit. regex is a dependency of dateparser and it was updated yesterday with the version 2019.12.9.

It is a good pratice to fix the version of all dependencies when you release a version of a lib because without changing the version of a lib, it might crash because a dependency has changed.

thanks for your job on this lib :)

**Comment by Gallaecio** [comment] 2019-12-10 20:09
Fixing dependency versions makes sense on applications using those libraries, but I don’t think libraries are meant to have fixed versions of dependencies, only version checks to ensure that compatible dependency versions are used.

**Comment by Gallaecio** [comment] 2019-12-11 11:08
May this be a duplicate of https://github.com/scrapinghub/dateparser/issues/505?

**Comment by Lenny415** [comment] 2019-12-11 12:08
This is similar, you're right!
As I said, the problem with a library not fixing dependencies (with a single version or a range) is that you can't ensure that the version of the lib you released will still work when a new version of a dependency will be.
And even a range of versions is complex to achieve when the dependency you use doesn't respect the semantic versioning.

**Comment by Gallaecio** [comment] 2019-12-11 12:12
I was wrong then, this is definitely something we need to do. Let us close this and keep track of this issue at #505.

**Comment by Gallaecio** [comment] 2019-12-13 11:07
#505 is about a specific issue with `2019.02.19`, and I think the way to solve it is to change the entry in `setup.py` to `regex !=2019.02.19` (although it probably does not really affect anyone at this point).

That does not apply here, though. It sounds like the latest regex does work with dateparser, it simply requires `gcc`. If things worked fine after installing `gcc`, I think there’s nothing we should change in `dateparser`. You can, and probably should, freeze versions on your end, as I suggested in [my first comment](https://github.com/scrapinghub/dateparser/issues/597#issuecomment-564223641).

**Comment by Lenny415** [comment] 2019-12-13 15:25
I don't think any version of regex should work. Imagine they change the contract (parameters or result) of a function you use in your code then a previously functionnal release will not work any more.
I may add that fixing the regex version on our end is not a good practice when using loose coupling. I should not have to be aware that when I use dateparser lib I have to install the regex lib or fixing its version.

**Comment by Gallaecio** [comment] 2020-02-19 16:30
If you use dateparser along with a different library that also uses regex, if each library pins a different version, you are screwed.

Instead, we need to define in `setup.py` a range of versions of `regex` that _should_ work with `dateparser`.

**Comment by noviluni** [comment] 2020-05-20 13:58
I agree with @Gallaecio and I will close this issue because this was fixed when we merged this: https://github.com/scrapinghub/dateparser/pull/600. 

Feel free to reopen the issue if you consider that it's not solved.

**Closed by noviluni** 2020-05-20 13:58 UTC
