### ISSUE TITLE
15-12-18 06:00 being parsed as 2018, Dec 15

### ISSUE THREAD

**Issue by pykler** [scrapinghub/dateparser#134] opened 2015-12-18 21:29 UTC
`'15-12-18 06:00'` becomes `datetime.datetime(2018,12,15, 6, 0, 0)` which IMHO should not be the first pattern it would match. I ended up using strptime instead of dateparser.parse.

**Comment by asadurski** [comment] 2015-12-18 22:50
Just to explain the situation, day-month-year format is the prevailing one and I can imagine applications that prefer future dates.
To obtain the proper date, you should use `dateparser.parse("15-12-18 06:00", date_formats=["%y-%m-%d %H:%M"])`, which, I admit, would not be far from directly using `strptime`.

That said, I think this problem deserves a resolution in setting, so the issue is still valid.

**Comment by pykler** [comment] 2015-12-19 02:31
So that is something that is not documented, nowhere in your readme does it
show you can pass date formats

**Comment by pykler** [comment] 2015-12-19 02:32
Last think I want to say, mm/dd/yy is probably prevailing but I am not sure
mm-dd-yy would be. (Slash vs dash)

**Comment by asadurski** [comment] 2016-01-19 14:01
A comment about the docs - what about the part in https://github.com/scrapinghub/dateparser/blob/master/README.rst#popular-formats?

**Comment by waqasshabbir** [comment] 2016-06-16 06:59
@pykler we will keep ordering based on delimiters in our bucket list. Though, for now that #187 is merged, you can use new `DATE_ORDER` setting to address similar issues. 

```
In [4]: parse('15-12-18 06:00', settings={'DATE_ORDER': 'YMD'})
Out[4]: datetime.datetime(2015, 12, 18, 6, 0)
```

**Closed by waqasshabbir** 2016-06-16 06:59 UTC
Labels: easy, enhancement
