### ISSUE TITLE
can be prevent searching relative dates

### ISSUE THREAD

**Issue by Bipulkumarsingh** [scrapinghub/dateparser#525] opened 2019-05-14 10:15 UTC
I am looking for dates only in my string like 
"25th march 2015 , 26th july 2018 , i need this report today."

I need only dates when search using search.search_dates()
but it also showing today.

Is any way to prevent this.

**Comment by lopuhin** [comment] 2019-09-20 11:54
The same feature in the ``parse`` function would be great to have as well, or a simple way to tell that the date was relative.

**Comment by Gallaecio** [comment] 2019-12-12 11:57
May this be a duplicate of #312?

**Closed** 2020-03-06 10:09 UTC
Labels: Type: Enhancement

**Comment by noviluni** [comment] 2020-03-06 14:09
In the last version `0.7.4` this can be done through the `PARSERS` setting. :tada:
