### ISSUE TITLE
Dateparser returning None when using filler words.

### ISSUE THREAD

**Issue by LeptoFlare** [scrapinghub/dateparser#678] opened 2020-05-14 21:01 UTC
```py
>>> import dateparser
>>> dateparser.parse('Saturday May 16th at 8.30pm UTC')
>>> 
```

**Comment by noviluni** [comment] 2020-05-15 08:32
This happens because the point (`.`) doesn't work as time delimiter and there is already an issue to track this bug: https://github.com/scrapinghub/dateparser/issues/643

You can fix it by changing the point by a colon:
```
>>> dateparser.parse('Saturday May 16th at 8:30pm UTC')
datetime.datetime(2020, 5, 16, 20, 30, tzinfo=<StaticTzInfo 'UTC'>)

```

As a temporary workaround, you could also use `str.replace('.', ':')` with the date string.

Closed as duplicate of:  https://github.com/scrapinghub/dateparser/issues/643

Thanks for giving your feedback @LeptoFlare

**Closed by noviluni** 2020-05-15 08:32 UTC
