### ISSUE TITLE
'a' returns a valid date

### ISSUE THREAD

**Issue by jfrancos** [scrapinghub/dateparser#259] opened 2016-12-04 07:12 UTC
`date.DateDataParser().get_date_data('a')`
Returns
`{'date_obj': datetime.datetime(2016, 1, 4, 0, 0), 'period': 'month', 'language': 'en'}`

also, single letters `d`, `h`, `j`, `k`, `l`, `m`, `s`, and `v` also return valid dates, some with `'en'` as the detected language, as well as other languages.

OS: macOS 10.12.1

**Comment by jfrancos** [comment] 2016-12-05 23:22
Update, seems related - "and a" returns January, i.e.:
`DateDataParser(languages=['en'], settings={ 'RELATIVE_BASE' : datetime(5000, 6, 15) }  ).get_date_data('and a')`
Returns
`{'date_obj': datetime.datetime(5000, 1, 15, 0, 0), 'period': 'month', 'language': 'en'}`

**Comment by waqasshabbir** [comment] 2016-12-08 11:31
Interesting bug. So 'D' gets translated to 'Sunday' in [ro language](https://github.com/scrapinghub/dateparser/blob/master/data/languagefiles/ro.yaml#L26) that's why it gives:

```
In [16]: DateDataParser().get_date_data('d')
Out[16]:
{'date_obj': datetime.datetime(2016, 12, 4, 0, 0),
 'language': 'ro',
 'period': 'day'}
```

Similarly for [en language](https://github.com/scrapinghub/dateparser/blob/master/data/languagefiles/en.yaml#L105) `a` translates to `1` and since the default order is `MDY` it assumes `1` to be the month (january).

**Comment by jfrancos** [comment] 2016-12-16 17:13
In the meantime, how can I instantiate a DateDataParser that ignores "simplifications"?

**Comment by noviluni** [comment] 2020-07-03 18:55
As we closed this: https://github.com/scrapinghub/dateparser/issues/655 should we close this issue?

Should we allow to ignore simplifications? does have this any real use case or it's just for this weird requirement?

cc: @Gallaecio

**Comment by lopuhin** [comment] 2020-07-06 08:40
I think this and #655 are duplicates. Re #655 closure - as I understand it's more of a "won't fix" (fixing it does not look feasible), not that it's an expected behaviour to treat "1" or "a" as a valid date?

**Comment by noviluni** [comment] 2020-11-22 18:44
Closing this issue. The reasons are explained in this comment: https://github.com/scrapinghub/dateparser/issues/330#issuecomment-731809713

Thank you for your feedback!

**Closed by noviluni** 2020-11-22 18:44 UTC
Labels: wont fix
