### ISSUE TITLE
strange behaviour on italian dates format

### ISSUE THREAD

**Issue by Fulvioo** [scrapinghub/dateparser#418] opened 2018-06-04 14:42 UTC
```
date = 'gio, 14 dic 2017 23:48:22 CET'
parse(date)
datetime.datetime(2017, 12, 14, 23, 48, 22, tzinfo=<StaticTzInfo 'CET'>)
```
-> OK
```
date="gio, 06 ott 2016 09:43:16 CEST"
parse(date)
datetime.datetime(2016, 10, 6, 9, 43, 16, tzinfo=<StaticTzInfo 'CEST'>)
```
-> OK
```
date = 'mar, 20 set 2016 09:39:59 CET'
parse(date)
None
```
**-> KO**
Why this, while all shuld be valid?

**Comment by Fulvioo** [comment] 2018-06-04 15:02
ps. same bahavoiurs using
`parse(date, date_formats=['%a, %d %b %Y'], languages=['it'])`

**Comment by Fulvioo** [comment] 2018-06-04 15:32
Issue found:
it might have been caused by having the same shortname for:
- martedì (tuesday) - "mar"
- marzo (march) - "mar"
Possible solution:
cut the date[4:]

**Comment by Gallaecio** [comment] 2019-12-11 12:23
Duplicate of #337

**Closed by Gallaecio** 2019-12-11 12:23 UTC
