### ISSUE TITLE
PytzUsageWarning

### ISSUE THREAD

**Issue by andreas-vester** [scrapinghub/dateparser#1017] opened 2021-11-10 14:15 UTC
I'm using a third party library that makes use of ``dateparser``. I do get a warning when hitting the following line:

https://github.com/scrapinghub/dateparser/blob/5ec1a6ea51963ba4006de4b79eaad4ddd80a8030/dateparser/date_parser.py#L35

PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html

**Comment by Gallaecio** [comment] 2021-11-15 07:02
Duplicate of #1013

**Closed by Gallaecio** 2021-11-15 07:02 UTC
