### ISSUE TITLE
New ruamel.yaml issues warning

### ISSUE THREAD

**Issue by DmitryBondarenko** [scrapinghub/dateparser#254] opened 2016-11-24 13:25 UTC
```
C:\Python34\lib\site-packages\dateparser\conf.py:47: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  cls._yaml_data = load_yaml(data).pop('settings', {})
C:\Python34\lib\site-packages\dateparser\languages\loader.py:46: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(data)
```

https://bitbucket.org/ruamel/yaml

0.13.0 (2016-11-20):
if load() or load_all() is called with only a single argument (stream or string) a UnsafeLoaderWarning will be issued once. If appropriate you can surpress this warning by filtering it. Explicitly supplying the Loader=ruamel.yaml.Loader argument, will also prevent it from being issued. You should however consider using safe_load(), safe_load_all() if your YAML input does not use tags.
allow adding comments before and after keys (based on StackOveflow Q&A by msinn)

**Comment by redapple** [comment] 2016-11-24 13:47
@DmitryBondarenko , thanks fore reporting. It's a duplicate of https://github.com/scrapinghub/dateparser/issues/251
This was fixed and merged yesterday in "master" (https://github.com/scrapinghub/dateparser/pull/252)

**Closed by redapple** 2016-11-24 13:47 UTC
