### ISSUE TITLE
How can i add custom keys for language detection

### ISSUE THREAD

**Issue by FahriBilici** [scrapinghub/dateparser#656] opened 2020-04-13 06:45 UTC
I want to add my custom keys and dates. how can i add ?

**Comment by noviluni** [comment] 2020-04-13 06:51
Hi @FahriBilici! Could you give us an example?

**Comment by FahriBilici** [comment] 2020-04-13 07:31
@noviluni like keys in the data/date_translation_data/tr.py . in relative-type key i will add religious holidays. for example i will add Eid al-Fitr and i will add ramadan as value than if i send ramadan to parser then it will return spesific date.

**Comment by Gallaecio** [comment] 2020-04-15 12:52
https://dateparser.readthedocs.io/en/latest/contributing.html#guidelines-for-editing-translation-data would be a good starting point on how to extend data. I’m not sure if the files already support this type of change, though; if not, we could work on adding it.

**Comment by FahriBilici** [comment] 2020-04-15 12:54
thanks @Gallaecio

**Comment by JanaPitanga** [comment] 2020-04-26 12:54
I have the same question, I would like to add relative dates for the French language. Were you able to add the dates you wanted @FahriBilici ? Or we really need a pull request @Gallaecio ?

Thanks!!! :)

**Comment by Gallaecio** [comment] 2020-04-27 18:59
Feel free to create a pull request following the instructions at https://dateparser.readthedocs.io/en/latest/contributing.html#guidelines-for-editing-translation-data

**Comment by FahriBilici** [comment] 2020-05-20 12:35
@Gallaecio i checked and tried guideline and i got many errors . i am trying to fix them but i have question. after i added new keys how dateparser will understand and return to me time?

**Comment by noviluni** [comment] 2020-05-20 13:46
Hi @FahriBilici, the script was failing because I fixed some conflicts wrongly, sorry :pray: 

[Now is fixed in master](https://github.com/scrapinghub/dateparser/pull/692), so you should be able to run it correctly. However, I will explain you step by step what you have to do:

1) Download this package: `git clone git@github.com:scrapinghub/dateparser.git` (or update it by doing: `git pull`).
2) Create a `virtualenv`.
3) Install that package in that virtual env (and the dependencies) locally by doing: `pip install -e .` (you have to be inside the `dateparser` folder).
4) Edit the `yaml` file you need to change inside the `dateparser/dateparser_data/supplementary_language_data/date_translation_data/` folder. For example, if you want to change the Spanish data you have to edit the `es.yaml` file. Most of the data has English as a reference, but there is also regex, etc. You can see the other `yaml` files in other languages to understand how it works.
5) Once you added the data you want, you have to run the script  `write_compelte_data.py`. To do it install the scripts requirements: `pip install -r scripts/write_complete_data.py` and then run the script by doing: `python scripts/write_complete_data.py`.

Then you can try if it works running `python` or `ipython` in that virtual env and importing `dateparser`.

@FahriBilici let me know if it works for you!


cc: @JanaPitanga

**Comment by FahriBilici** [comment] 2020-05-21 09:57
@noviluni i tried today again ant it gives me no module errors. after i fix them by installing modules via pip it gives me this error : 
`Traceback (most recent call last):
  File "scripts/write_complete_data.py", line 133, in <module>
    write_complete_data()
  File "scripts/write_complete_data.py", line 98, in write_complete_data
    date_translation_data = _get_complete_date_translation_data(language)
  File "scripts/write_complete_data.py", line 60, in _get_complete_date_translation_data
    with open(supplementary_date_directory + language + '.yaml') as g:
FileNotFoundError: [Errno 2] No such file or directory: '../dateparser_data/supplementary_language_data/date_translation_data/.ipynb_checkp.yaml'`

**Comment by Gallaecio** [comment] 2020-06-24 11:24
It looks like you have a file somewhere called `.ipynb_checkp.py`, and the script is not ready to ignore that file.

**Comment by noviluni** [comment] 2020-11-26 15:51
I will close this issue as it's not a bug neither a feature request. If you need support using dateparser you can use StackOverflow.

Please, feel free to reopen the ticket if yout think there is anything wrong with the library :)

**Closed by noviluni** 2020-11-26 15:51 UTC
